### ISSUE TITLE
include port in the scanning process 

### ISSUE THREAD

**Issue by aminbp** [0xPwny/Apkatshu#1]
Is it possible to include port as part of IP and URL scanning? It will be a great help

**Comment by haroonawanofficial** [comment]
I already did. I will merge request also python3 version, if author allow me.

I added:
Ports,
IPs,
Domains,
Queries,
Schemes,
Interesting files are updated,
Private connection....

Hopefully author allow me. Try the same ersion here:
Https://github.com/haroonawanofficial/Flame

Author name is remained in the tool. Tool works very fast now. More update is being done right now in python3 environment.

**Comment by 0xPwny** [comment]
yeah i will add many features in the present , thanks for using this tool and for helping me to improve it !

**Comment by 0xPwny** [comment]
ip and port extraction  and validation added :)
