### ISSUE TITLE
Indentation errors

### ISSUE THREAD

**Issue by SSHbabe** [0xPwny/Apkatshu#3]
during the time that your python script gets ran, it has a bunch of indentation errors, i would assume you have different indentation settings but even my friend wasn't able to run the script without running into errors. when you also reset all the indentation style in the script, errors still appear.

**Comment by SSHbabe** [comment]
I'll pull request a script, you could improve it by simply adding pretty output, as that's all it needs.

**Comment by 0xPwny** [comment]
can you please copy the errors here so i can identify whats the problem .

**Comment by SSHbabe** [comment]
`
File "Extractshu.py", line 50
    ex_urls = list(set(re.findall(r'(?:https?|ftp):\/\/[\w/\-?=%.]+\.[\w/\-?=%.]+', data)))
                                                                                          ^
TabError: inconsistent use of tabs and spaces in indentation
`

**Comment by xorist** [comment]
![Screenshot_20191201-152857_Termux](https://user-images.githubusercontent.com/42919907/69920594-7cfabb00-144f-11ea-9c6f-004dcc7db039.jpg)

**Comment by xorist** [comment]
This error means that in your indenting while writing python code, you've used tabs and spaces interchangeably. Just go through and make sure everything is either tabs or spaces.

**Comment by 0xPwny** [comment]
yeah exactly @xorist  , ill fix this

**Comment by 0xPwny** [comment]
can anyone confirm if the problem still occurs or fixed !

**Comment by SSHbabe** [comment]
for me it still exists. But I'll keep checking.

**Comment by SSHbabe** [comment]
@0xPwny can you show us if it's working for you.

**Comment by xorist** [comment]
Just pulled and tested again, still exists.

**Comment by 0xPwny** [comment]
![Screenshot_2019-12-01_17-16-46](https://user-images.githubusercontent.com/16179243/69921293-71fb5700-145e-11ea-8dc3-708c49e59b48.png)

for me everything works fine

**Comment by xorist** [comment]
That's very weird, can you copy your entire file and posts it to like a pastebin and link it here?

**Comment by 0xPwny** [comment]
its the same , i  pulled the repo with the new modifications nd i ran it

**Comment by SSHbabe** [comment]
@0xPwny it turns out the issue was that we were running it on python 3, in your bash command the "python" command to our system is by default python 3 so we had to switch it to python 2, you may want to include in the readme that this only works on python 2.
