### ISSUE TITLE
TabError in Line 67 - Extractshu.py

### ISSUE THREAD

**Issue by nanna7077** [0xPwny/Apkatshu#8]
![apkatshu_error](https://user-images.githubusercontent.com/62479349/85915616-a5705980-b866-11ea-9b02-9b73110c9b2e.png)

**Comment by 0xPwny** [comment]
which python version you use ?

**Comment by nanna7077** [comment]
3.7

**Comment by cyberjj999** [comment]
@nanna7077, try changing 'python Extractshu.py $dist_dir $Tool' to 'python2 Extractshu.py $dist_dir $Tool' in line 89 of Apkatshu.sh, it works for me.
When I changed it to python3, I get the same error as you, I guess the tool doesn't support python3 yet

**Comment by nanna7077** [comment]
Thanks a lot!
